// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SelfServicePortal.Data;

#nullable disable

namespace SelfServicePortal.Migrations
{
    [DbContext(typeof(SelfServicePortalContext))]
    partial class SelfServicePortalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("SelfServicePortal.Models.ApplicationUsers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdGroup")
                        .HasColumnType("TEXT");

                    b.Property<string>("Appgroup")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ApplicationUsers");
                });

            modelBuilder.Entity("SelfServicePortal.Models.DepotMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ADGroup")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Depot")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DepotMapping");
                });
#pragma warning restore 612, 618
        }
    }
}
